### ISSUE TITLE
All tests timeout on fresh API generation on Windows 10.

### ISSUE THREAD

**Issue by misleadingTitle** [diegohaz/rest#106]
On a fresh generation of the REST API on Windows 10 all the tests timeout with errors similar to this:
```
FAIL  src\services\response\index.test.js (16.109s)
  ● success › responds with passed object and status 200

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at Timeout._onTimeout (node_modules\jest-jasmine2\vendor\jasmine-2.5.2.js:1979:23)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

I've tried to get the exact packages version listed in the npm package (instead of the most recent ones) but nothing changed. I've also tried on differend windows machines (both Windows 10 and 7) without success. Node and mongo are updated to latest versions.

I haven't found anyone else with this issue so far and it seems strange. What can be the problem?

It might be partially mockgoose related since removing the mock and using a real database makes the firsts tests pass but then, after an handful of passed tests, all the following cases timeout.

Any idea?

**Comment by hboylan** [comment]
I'm having the same issue on Windows 8.1

Also tried running jest with the `-i` or `--runInBand` flag (as per [this Jest issue](https://github.com/facebook/jest/issues/3079)), which does not work.

**Comment by maustand** [comment]
Hi
I am working on ubuntu 16.4 and my co workers on mac and it works perfect.
Did you update your dependencies ?

There is a problem if you update mockgoose to the lastest version, it would not work.

Could you provide us more details ?

Regards

**Comment by hboylan** [comment]
@maustand Thanks for the reply.

Using the same code base on Mac last night, I was able to run all of the `generator-rest` tests in ~8s. Still having the same issue on Windows today.

The core [issue](https://github.com/facebook/jest/issues/3630) appears to be an ongoing bug with Jest's parallelization on Windows.

(Adding `--runInBand` doesn't fix the problem for me).

**Comment by hboylan** [comment]
So commenting out `mockgoose` in `test/setup.js` allows `jest -i` to run properly. 

Neither v6.0.8 (generator default) or v7.3.3 (latest release) of mockgoose are working.
Do you know a version that does?

**Comment by maustand** [comment]
@hboylan Sadly i dont have windows and i could not reproduce this bug in my pc.
Anyway lets see if the jest team can fix and i will update the dependencies again.

Currently i working on ubuntu 16.4,  
nodejs  v6.11.4 
jest-cl": "^20.0.4",
mockgoose: "^6.0.8",

So It works perfect, but i tried to update to a newer version of mockgoose and it does not work, even if you update jest to v21.0.0 or a newer version, it does not work too..


If you need, i could send you my configuration or just check[ this package.json](https://github.com/diegohaz/rest/blob/master/generators/app/templates/_package.json)

Regards

**Comment by hboylan** [comment]
Thanks for looking into it. Windows always has the best Node bugs. ;)

For now, running Jest in serial without Mockgoose is a viable solution. It didn't work for me, but I noticed the Mockgoose [example ](https://www.npmjs.com/package/mockgoose#example) wraps Mongoose with `prepareStorage()`.

I can help clean dependencies and/or deprecation warnings if you like.

**Comment by maustand** [comment]
I updated the dependencies 2 weeks ago but PR are  welcome !
Go ahead !
Thanks you so munch !

**Comment by hboylan** [comment]
Hey, I figured out why Mockgoose isn't working!

✖️ 
```es6
import mockgoose from 'mockgoose'
import mongoose from 'mongoose'

beforeAll(async () => {
  await mockgoose(mongoose)
  mongoose.connect(mongo.uri)
})
```

✔️ 
```es6
import {Mockgoose} from 'mockgoose'
import mongoose from 'mongoose'

const mockgoose = new Mockgoose(mongoose)

beforeAll(async () => {
  await mockgoose.prepareStorage()
  await mongoose.connect(mongo.uri, mongo.opts)
})
```

@misleadingTitle This fixes the timeout issue for me.

**Comment by misleadingTitle** [comment]
Thanks @hboylan, this fixed it for me too!

**Comment by marcoshuck** [comment]
@hboylan hey, I have been trying your fix but it doesn't work. This is what I got

```
Test suite failed to run
TypeError: _mockgoose.Mockgoose is not a constructor
```

Any idea why?

**Comment by hboylan** [comment]
@marcoshuck I forget the specific reason for that error, but I think it had something to do with the mockgoose version being used. For instance, maybe updating to the latest version of it breaks that syntax...
