### ISSUE TITLE
Cant deploy on heroku get node error

### ISSUE THREAD

**Issue by AlbertoIHP** [diegohaz/rest#139]
When i see logs, this is showed:

`> wasapi@0.0.0 start /app
> node .

/app/src/services/mongoose/index.js:23
(0, _keys2.default)(_config.mongo.options).forEach(function (key) {
                   ^

TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Object.<anonymous> (/app/src/services/mongoose/index.js:5:1)
    at Module._compile (module.js:635:30)
    at loader (/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/src/app.js:3:1)
    at Module._compile (module.js:635:30)
    at loader (/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/src/index.js:3:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wasapi@0.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wasapi@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-12-18T04_31_49_877Z-debug.log
`

**Comment by amanforindia** [comment]
src/config.js -> add "options: {}" to config.production.mongo

**Comment by Selyuu** [comment]
@amanforindia Thank you!
