### ISSUE TITLE
npm run prod throws an error

### ISSUE THREAD

**Issue by semsenya** [diegohaz/rest#172]
Hi and thanks for your work!
It works fine in dev, but when  I try to run npm run prod, it throws an error:

$ npm run prod

> _api-name_@0.0.0 prod _api-directory_
> cross-env NODE_ENV=production nodemon -i "*.test.js" -r dotenv-safe/config .

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node -r dotenv-safe/config .`
_path-to-api_/src/services/mongoose/index.js:23
(0, _keys2.default)(_config.mongo.options).forEach(function (key) {
_______________^

TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Object.<anonymous> (_path-to-api_/src/services/mongoose/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (_path-to-api_/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (_path-to-api_/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (_path-to-api_/src/app.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (_path-to-api_/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (_path-to-api_/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (_path-to-api_/src/index.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
[nodemon] app crashed - waiting for file changes before starting...

I'm trying to deploy it on digitalocean (Ubuntu 16.04), however the same error occurs on my local machine as well. Not quite sure what am I doing wrong.
Kind regards,
Semyon.

**Comment by semsenya** [comment]
Added options: {} to config.production.mongo in src/config.js, problem solved.
