### ISSUE TITLE
App not recognising env file

### ISSUE THREAD

**Issue by CasperGrey** [diegohaz/rest#185]
Hi, When i try to run the app for the first time , i get

 themeo-api@0.0.0 start /app
2018-08-17T23:42:50.733534+00:00 app[web.1]: > node .
2018-08-17T23:42:50.733535+00:00 app[web.1]:
2018-08-17T23:42:52.263269+00:00 app[web.1]: /app/src/config.js:21
2018-08-17T23:42:52.263299+00:00 app[web.1]: throw new Error('You must set the ' + name + ' environment variable');
2018-08-17T23:42:52.263302+00:00 app[web.1]: ^
2018-08-17T23:42:52.263303+00:00 app[web.1]:
2018-08-17T23:42:52.263305+00:00 app[web.1]: Error: You must set the SENDGRID_KEY environment variable
2018-08-17T23:42:52.263307+00:00 app[web.1]: at requireProcessEnv (/app/src/config.js:8:11)
2018-08-17T23:42:52.263308+00:00 app[web.1]: at Object.<anonymous> (/app/src/config.js:30:18)
2018-08-17T23:42:52.263310+00:00 app[web.1]: at Module._compile (module.js:652:30)
2018-08-17T23:42:52.263312+00:00 app[web.1]: at loader (/app/node_modules/babel-register/lib/node.js:144:5)
2018-08-17T23:42:52.263314+00:00 app[web.1]: at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2018-08-17T23:42:52.263316+00:00 app[web.1]: at Module.load (module.js:565:32)
2018-08-17T23:42:52.263318+00:00 app[web.1]: at tryModuleLoad (module.js:505:12)
2018-08-17T23:42:52.263319+00:00 app[web.1]: at Function.Module._load (module.js:497:3)
2018-08-17T23:42:52.263320+00:00 app[web.1]: at Module.require (module.js:596:17)
2018-08-17T23:42:52.263322+00:00 app[web.1]: at require (internal/module.js:11:18)
2018-08-17T23:42:52.273511+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-08-17T23:42:52.273980+00:00 app[web.1]: npm ERR! errno 1
2018-08-17T23:42:52.275644+00:00 app[web.1]: npm ERR! themeo-api@0.0.0 start: `node .`
2018-08-17T23:42:52.275830+00:00 app[web.1]: npm ERR! Exit status 1
2018-08-17T23:42:52.276100+00:00 app[web.1]: npm ERR!
2018-08-17T23:42:52.276291+00:00 app[web.1]: npm ERR! Failed at the themeo-api@0.0.0 start script.
2018-08-17T23:42:52.276447+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I have correctly filled out the env file with my keys 

SENDGRID_KEY=< my key here >
MASTER_KEY= < my key here >
JWT_SECRET=  < my key here >

and package.json the same as yours

  "scripts": {
    "start": "node .",
    "test": "jest",
    "coverage": "npm test -- --coverage",
    "postcoverage": "opn coverage/lcov-report/index.html",
    "development": "nodemon -i \"*.test.js\" .",
    "production": "cross-env NODE_ENV=production nodemon -i \"*.test.js\" -r dotenv-safe/config .",
    "lint": "eslint src",
    "docs": "apidoc -i src -o docs && apidoc-markdown -p docs -o DOCS.md",
    "postdocs": "opn docs/index.html"
  },

**Comment by diegohaz** [comment]
@CasperGrey Does it happen on a clean install? I mean, without changing any files after generating the project? If so, could you put it in a repository so we can reproduce the issue?

**Comment by CasperGrey** [comment]
A clean isntall fixed it - thanks - not sure what i had in there that was conflicting . If you dont add authentication on API create - how do you add it later?

**Comment by diegohaz** [comment]
Nice.

Currently, if you want to add authentication later you should do that manually.
